### ISSUE TITLE
Requirements?

### ISSUE THREAD

**Issue by Lucaweihs** [vincentcartillier/Semantic-MapNet#1]
Hi @vincentcartillier,

Would you be able to provide a `requirements.txt` (or `environment.yml` if you use conda) for this project? Also, there seem to be some imports, e.g.
```python
from metric.metrics import averageMeter
from metric.iou import IoU
```
which I suspect might correspond to a missing `metric.py` file?

Finally, under your license section you have listed BDS. Is this meant to be BSD? If so, is this the [standard 3-clause variant](https://opensource.org/licenses/BSD-3-Clause)?

**Comment by vincentcartillier** [comment]
Hi @Lucaweihs 

Thanks for your feedback.

I've added a requirements.txt and missing dependencies (metric).

The license is BSD (sorry for the typo here)

I've also included a demo.py file.

Let me know if you have further questions.
Thanks!
