### ISSUE TITLE
Recompute the GT semantic maps

### ISSUE THREAD

**Issue by Abundant-me** [vincentcartillier/Semantic-MapNet#11]
Hi, vincentcartillier. Thanks for your intelligent works.

I want to recompute the point clouds and GT topdown semantic maps since the download link does not contain all the scenes in mp3d.

Here is what I do. I first run `data/build_point_cloud_from_mesh.py` and then run `compute_GT_topdown_semantic_maps/build_semmap_from_obj_point_cloud.py`.
Here is the problem I meet. In the first step, it generate '.ply' files. In the second step, it tries to load '.h5' files at line 24 and it can not load the generated '.ply' files successfully.

Do I miss anything? Hope your reply. Thanks!

**Comment by vincentcartillier** [comment]
Hi, 
Thanks for reaching out. 
I have added a script that computes the semantic point cloud and save it as a .h5 file: 
`data/build_point_cloud_from_mesh_h5.py`

Try this out and let me know if that works.

**Comment by Abundant-me** [comment]
Thanks for your reply.

The new script does work. But I meet other problem as follows:

When I run `compute_GT_topdown_semantic_maps/build_semmap_from_obj_point_cloud.py`, it raise an IndexError at line 119 and 122: `IndexError: index 3213656 is out of bounds for dimension 0 with size 3213656`
I guess the index should subtract 1 like `flat_map_instance[m.view(-1)] = obj_ids[argmax_flat_spatial_map[m] - 1]` for line 119, the same for 122.

When I try the modification as above, I can generate semantic map successfully. But the map does not contain the background class, i.e., `map_semantic` does not contain value 0 and `map_instance` does not contain value -1. Maybe my modification is wrong?

**Comment by vincentcartillier** [comment]
The generated ground-truth maps should contain background information. Any pixel that does not represent an object of interest should have a value of 0 in the map_semantic and -1 in the map_instance.

What version of torch_scatter are you using? (SMNet works with the 1.4.0 version)

**Comment by Abundant-me** [comment]
The version of torch_scatter that I use is 2.0.5. It is higher than what SMNet needs. Should I have to change the version?

**Comment by vincentcartillier** [comment]
Yes that would do it. torch_scatter >2.0 has major modifications. You should switch to 1.4.0.

**Comment by Abundant-me** [comment]
I change the version of torch_scatter to 1.4.0 and it figures out my problem.

Thanks a lot!
