### ISSUE TITLE
Training data size

### ISSUE THREAD

**Issue by BeaTrier** [vincentcartillier/Semantic-MapNet#12]
1. I was computing the training data on the server, but the administrator told me that I have exceeded my BLOCK quota limits and the computing progress have not finished. So I want to know how big is the training dataset?

2. Would you mind letting me know the minimum GPU capacity requirement for running the code?

Thanks in advance!

**Comment by vincentcartillier** [comment]
The training data is about 1.4T. The preprocessing script will save the intermediate egocentric features for all 20 steps in the training episode. Each egocentric feature map has a dimension of 240x320x64, with 20 frames per episode and roughly 3400 episodes in train and val, this leads to ~1.4T.
One solution to overcome this is to only save the images during the preprocessing step and then compute the egocentric features during training. 

We trained SMNet with a batch size of 8 over 8 TitanXps (each has 12G memory). Depending on your application I believe it could be possible to finetune SMNet on a smaller set of GPUs with a smaller batch size.

**Comment by BeaTrier** [comment]
Hi,

Thanks for your intelligent work.
Would you be able to provide the ground truth map and path info of Replica? I noticed that you also test it on Replica, but it's not available on this repo.
Thanks a lot!
