### ISSUE TITLE
Question about demo.py result

### ISSUE THREAD

**Issue by rpartsey** [vincentcartillier/Semantic-MapNet#16]
Hi, I'm curious what the expected `demo.py` visualisation should be.

This is the plot I get after running `demo.py` for 100 steps (N = 100 [here](https://github.com/vincentcartillier/Semantic-MapNet/blob/e64470e69930260939efd9473f02be86979406ce/demo.py#L93))
![myplot](https://user-images.githubusercontent.com/37709869/192614817-8eac7c1d-b0ea-49df-a7b6-24c41c7111ed.png)

This is the plot I get after running `demo.py` for all the steps.
![myplot2](https://user-images.githubusercontent.com/37709869/192614894-3ee93cba-0436-4726-a552-e2b8e0debceb.png)

I expect a nice semantic topdown map to be visualised. Any ideas what might went wrong?
Thanks in advance!

**Comment by vincentcartillier** [comment]
You should expect to see a result similar as in the paper (eg. fig 4).
This result is indeed odd. Could this be some version mismatch ? (I've seen weird results in the past with newer versions of torch-scatter). 
You can check the versions I've used in the requirements.txt

**Comment by rpartsey** [comment]
@vincentcartillier Thanks for the prompt response.
Oh, yes, I do have a newer version of the `torch-scatter` than specified in the Readme (my Nvidia driver and cuda doesn't support older versions of `torch-scatter`:( ).

**Comment by rpartsey** [comment]
I'd like to add that when all the dependencies requirements are met `demo.py` produces the result as expected.
See the image attached:
![demo](https://user-images.githubusercontent.com/37709869/204764726-56a6fbbd-f7f9-4efa-9280-7ca68c6aa9c2.png)
