### ISSUE TITLE
ground-truth topdown semantic maps

### ISSUE THREAD

**Issue by sanghongrui** [vincentcartillier/Semantic-MapNet#2]
Thanks for your intelligent works.
Would you be able to provide codes about creating ground-truth topdown semantic maps?

**Comment by vincentcartillier** [comment]
Hi jaonsanggit,
Thanks for your interest in the project!
The precomputed GT topdown semantic maps can be downloaded directly.

To re-compute those from the object point clouds you can run the following:

`python compute_GT_topdown_semantic_maps/build_semmap_from_obj_point_cloud.py
`
