### ISSUE TITLE
The semantic dense point cloud of objects with cleaned floor labels and Ground truth top-down semantic maps Link addresses are not available

### ISSUE THREAD

**Issue by lushengyang222** [vincentcartillier/Semantic-MapNet#6]

**Comment by lushengyang222** [comment]
Thank you for sharing, but some URL links in the readme have expired, can you share it again?

**Comment by vincentcartillier** [comment]
Hey @lushengyang222 , I have just updated the sharing links. You should be able to download the data now.
Thanks for the heads-up!
