### ISSUE TITLE
Generating Path

### ISSUE THREAD

**Issue by ugurbolat** [vincentcartillier/Semantic-MapNet#7]
Hey @vincentcartillier,

I was wondering how you generated the navigation path in Matterport dataset. 

Did you write function/script to generate the explorative actions to cover the whole area or was it record manually?

I might implement sth similar for new ReplicaCAD dataset for Habitat or other datasets.

Ugur

**Comment by vincentcartillier** [comment]
Hi @ugurbolat ,

Those trajectories were manually recorded. You can take a look at this tutorial (https://colab.research.google.com/github/facebookresearch/habitat-sim/blob/master/examples/tutorials/colabs/ECCV_2020_Navigation.ipynb) on how to generate trajectories using Habitat.

**Comment by ugurbolat** [comment]
Thanks!

Will check out.
